const elements = [
    { symbol: "H", name: "Hydrogen", number: 1, description: "A colorless, odorless gas.", category: "nonmetal", column: 1, row: 1 },
    { symbol: "He", name: "Helium", number: 2, description: "A noble gas, used in balloons.", category: "noble gas", column: 18, row: 1 },
    { symbol: "Li", name: "Lithium", number: 3, description: "Used in batteries.", category: "alkali metal", column: 1, row: 2 },
    { symbol: "Be", name: "Beryllium", number: 4, description: "Used in aerospace.", category: "alkaline earth metal", column: 2, row: 2 },
    { symbol: "B", name: "Boron", number: 5, description: "Used in glass.", category: "metalloid", column: 13, row: 2 },
    { symbol: "C", name: "Carbon", number: 6, description: "The basis of life.", category: "nonmetal", column: 14, row: 2 },
    { symbol: "N", name: "Nitrogen", number: 7, description: "Found in the atmosphere.", category: "nonmetal", column: 15, row: 2 },
    { symbol: "O", name: "Oxygen", number: 8, description: "Essential for life.", category: "nonmetal", column: 16, row: 2 },
    { symbol: "F", name: "Fluorine", number: 9, description: "Highly reactive.", category: "halogen", column: 17, row: 2 },
    { symbol: "Ne", name: "Neon", number: 10, description: "Used in neon signs.", category: "noble gas", column: 18, row: 2 },
    { symbol: "Na", name: "Sodium", number: 11, description: "Reactive metal.", category: "alkali metal", column: 1, row: 3 },
    { symbol: "Mg", name: "Magnesium", number: 12, description: "Used in alloys.", category: "alkaline earth metal", column: 2, row: 3 },
    { symbol: "Al", name: "Aluminium", number: 13, description: "Lightweight metal.", category: "post-transition metal", column: 13, row: 3 },
    { symbol: "Si", name: "Silicon", number: 14, description: "Used in electronics.", category: "metalloid", column: 14, row: 3 },
    { symbol: "P", name: "Phosphorus", number: 15, description: "Essential element for life.", category: "nonmetal", column: 15, row: 3 },
    { symbol: "S", name: "Sulfur", number: 16, description: "Used in fertilizers.", category: "nonmetal", column: 16, row: 3 },
    { symbol: "Cl", name: "Chlorine", number: 17, description: "Disinfectant.", category: "halogen", column: 17, row: 3 },
    { symbol: "Ar", name: "Argon", number: 18, description: "Noble gas.", category: "noble gas", column: 18, row: 3 },
    { symbol: "K", name: "Potassium", number: 19, description: "Essential nutrient.", category: "alkali metal", column: 1, row: 4 },
    { symbol: "Ca", name: "Calcium", number: 20, description: "Strengthens bones.", category: "alkaline earth metal", column: 2, row: 4 },
    { symbol: "Sc", name: "Scandium", number: 21, description: "Transition metal.", category: "transition metal", column: 3, row: 4 },
    { symbol: "Ti", name: "Titanium", number: 22, description: "Strong and lightweight.", category: "transition metal", column: 4, row: 4 },
    { symbol: "V", name: "Vanadium", number: 23, description: "Used in steel alloys.", category: "transition metal", column: 5, row: 4 },
    { symbol: "Cr", name: "Chromium", number: 24, description: "Used in stainless steel.", category: "transition metal", column: 6, row: 4 },
    { symbol: "Mn", name: "Manganese", number: 25, description: "Essential for steelmaking.", category: "transition metal", column: 7, row: 4 },
    { symbol: "Fe", name: "Iron", number: 26, description: "Core of the Earth.", category: "transition metal", column: 8, row: 4 },
    { symbol: "Co", name: "Cobalt", number: 27, description: "Used in batteries.", category: "transition metal", column: 9, row: 4 },
    { symbol: "Ni", name: "Nickel", number: 28, description: "Corrosion-resistant metal.", category: "transition metal", column: 10, row: 4 },
    { symbol: "Cu", name: "Copper", number: 29, description: "Excellent conductor.", category: "transition metal", column: 11, row: 4 },
    { symbol: "Zn", name: "Zinc", number: 30, description: "Used to galvanize steel.", category: "transition metal", column: 12, row: 4 },
    { symbol: "Ga", name: "Gallium", number: 31, description: "Used in electronics.", category: "post-transition metal", column: 13, row: 4 },
    { symbol: "Ge", name: "Germanium", number: 32, description: "Semiconductor.", category: "metalloid", column: 14, row: 4 },
    { symbol: "As", name: "Arsenic", number: 33, description: "Toxic metalloid.", category: "metalloid", column: 15, row: 4 },
    { symbol: "Se", name: "Selenium", number: 34, description: "Used in photocopiers.", category: "nonmetal", column: 16, row: 4 },
    { symbol: "Br", name: "Bromine", number: 35, description: "Liquid halogen.", category: "halogen", column: 17, row: 4 },
    { symbol: "Kr", name: "Krypton", number: 36, description: "Noble gas.", category: "noble gas", column: 18, row: 4 },
  { symbol: "Rb", name: "Rubidium", number: 37, description: "Highly reactive alkali metal.", category: "alkali metal", column: 1, row: 5 },
  { symbol: "Sr", name: "Strontium", number: 38, description: "Used in fireworks.", category: "alkaline earth metal", column: 2, row: 5 },
  { symbol: "Y", name: "Yttrium", number: 39, description: "Used in lasers.", category: "transition metal", column: 3, row: 5 },
  { symbol: "Zr", name: "Zirconium", number: 40, description: "Resistant to corrosion.", category: "transition metal", column: 4, row: 5 },
  { symbol: "Nb", name: "Niobium", number: 41, description: "Used in superconducting magnets.", category: "transition metal", column: 5, row: 5 },
  { symbol: "Mo", name: "Molybdenum", number: 42, description: "Essential in enzymes.", category: "transition metal", column: 6, row: 5 },
  { symbol: "Tc", name: "Technetium", number: 43, description: "Radioactive and synthetic.", category: "transition metal", column: 7, row: 5 },
  { symbol: "Ru", name: "Ruthenium", number: 44, description: "Hard, rare transition metal.", category: "transition metal", column: 8, row: 5 },
  { symbol: "Rh", name: "Rhodium", number: 45, description: "Highly reflective.", category: "transition metal", column: 9, row: 5 },
  { symbol: "Pd", name: "Palladium", number: 46, description: "Used in catalytic converters.", category: "transition metal", column: 10, row: 5 },
  { symbol: "Ag", name: "Silver", number: 47, description: "Highly conductive.", category: "transition metal", column: 11, row: 5 },
  { symbol: "Cd", name: "Cadmium", number: 48, description: "Toxic metal.", category: "transition metal", column: 12, row: 5 },
  { symbol: "In", name: "Indium", number: 49, description: "Used in touchscreens.", category: "post-transition metal", column: 13, row: 5 },
  { symbol: "Sn", name: "Tin", number: 50, description: "Used in alloys.", category: "post-transition metal", column: 14, row: 5 },
  { symbol: "Sb", name: "Antimony", number: 51, description: "Used in flame retardants.", category: "metalloid", column: 15, row: 5 },
  { symbol: "Te", name: "Tellurium", number: 52, description: "Used in alloys.", category: "metalloid", column: 16, row: 5 },
  { symbol: "I", name: "Iodine", number: 53, description: "Essential nutrient.", category: "halogen", column: 17, row: 5 },
  { symbol: "Xe", name: "Xenon", number: 54, description: "Noble gas used in lamps.", category: "noble gas", column: 18, row: 5 },
  { symbol: "Cs", name: "Cesium", number: 55, description: "Soft, gold-colored alkali metal.", category: "alkali metal", column: 1, row: 6 },
  { symbol: "Ba", name: "Barium", number: 56, description: "Used in contrast agents for X-rays.", category: "alkaline earth metal", column: 2, row: 6 },
  { symbol: "La", name: "Lanthanum", number: 57, description: "Beginning of the lanthanides.", category: "lanthanide", column: 3, row: 9 },
  { symbol: "Ce", name: "Cerium", number: 58, description: "Most abundant rare earth element.", category: "lanthanide", column: 4, row: 9 },
  { symbol: "Pr", name: "Praseodymium", number: 59, description: "Used in aircraft engines.", category: "lanthanide", column: 5, row: 9 },
  { symbol: "Nd", name: "Neodymium", number: 60, description: "Used in powerful magnets.", category: "lanthanide", column: 6, row: 9 },
  { symbol: "Pm", name: "Promethium", number: 61, description: "Radioactive lanthanide.", category: "lanthanide", column: 7, row: 9 },
  { symbol: "Sm", name: "Samarium", number: 62, description: "Used in samarium-cobalt magnets.", category: "lanthanide", column: 8, row: 9 },
  { symbol: "Eu", name: "Europium", number: 63, description: "Used in fluorescent lamps.", category: "lanthanide", column: 9, row: 9 },
  { symbol: "Gd", name: "Gadolinium", number: 64, description: "Used in MRI contrast agents.", category: "lanthanide", column: 10, row: 9 },
  { symbol: "Tb", name: "Terbium", number: 65, description: "Used in green phosphors.", category: "lanthanide", column: 11, row: 9 },
  { symbol: "Dy", name: "Dysprosium", number: 66, description: "Used in hard magnets.", category: "lanthanide", column: 12, row: 9 },
  { symbol: "Ho", name: "Holmium", number: 67, description: "Strong magnetic properties.", category: "lanthanide", column: 13, row: 9 },
  { symbol: "Er", name: "Erbium", number: 68, description: "Used in fiber optics.", category: "lanthanide", column: 14, row: 9 },
  { symbol: "Tm", name: "Thulium", number: 69, description: "Rare lanthanide metal.", category: "lanthanide", column: 15, row: 9 },
  { symbol: "Yb", name: "Ytterbium", number: 70, description: "Used in atomic clocks.", category: "lanthanide", column: 16, row: 9 },
  { symbol: "Lu", name: "Lutetium", number: 71, description: "Last lanthanide.", category: "lanthanide", column: 17, row: 9 },
  { symbol: "Hf", name: "Hafnium", number: 72, description: "Used in nuclear control rods.", category: "transition metal", column: 4, row: 6 },
  { symbol: "Ta", name: "Tantalum", number: 73, description: "Highly corrosion-resistant.", category: "transition metal", column: 5, row: 6 },
  { symbol: "W", name: "Tungsten", number: 74, description: "Highest melting point.", category: "transition metal", column: 6, row: 6 },
  { symbol: "Re", name: "Rhenium", number: 75, description: "Used in jet engines.", category: "transition metal", column: 7, row: 6 },
  { symbol: "Os", name: "Osmium", number: 76, description: "Densest element.", category: "transition metal", column: 8, row: 6 },
  { symbol: "Ir", name: "Iridium", number: 77, description: "Highly corrosion-resistant.", category: "transition metal", column: 9, row: 6 },
  { symbol: "Pt", name: "Platinum", number: 78, description: "Precious metal.", category: "transition metal", column: 10, row: 6 },
  { symbol: "Au", name: "Gold", number: 79, description: "Highly valuable precious metal.", category: "transition metal", column: 11, row: 6 },
    { symbol: "Hg", name: "Mercury", number: 80, description: "Liquid metal at room temperature.", category: "transition metal", column: 12, row: 6 },
    { symbol: "Tl", name: "Thallium", number: 81, description: "Toxic post-transition metal.", category: "post-transition metal", column: 13, row: 6 },
    { symbol: "Pb", name: "Lead", number: 82, description: "Heavy metal used in batteries.", category: "post-transition metal", column: 14, row: 6 },
    { symbol: "Bi", name: "Bismuth", number: 83, description: "Heaviest stable element.", category: "post-transition metal", column: 15, row: 6 },
    { symbol: "Po", name: "Polonium", number: 84, description: "Radioactive metalloid.", category: "metalloid", column: 16, row: 6 },
    { symbol: "At", name: "Astatine", number: 85, description: "Rare radioactive halogen.", category: "halogen", column: 17, row: 6 },
    { symbol: "Rn", name: "Radon", number: 86, description: "Radioactive noble gas.", category: "noble gas", column: 18, row: 6 },
    { symbol: "Fr", name: "Francium", number: 87, description: "Highly radioactive alkali metal.", category: "alkali metal", column: 1, row: 7 },
    { symbol: "Ra", name: "Radium", number: 88, description: "Radioactive alkaline earth metal.", category: "alkaline earth metal", column: 2, row: 7 },
    { symbol: "Ac", name: "Actinium", number: 89, description: "First of the actinides.", category: "actinide", column: 3, row: 10 },
    { symbol: "Th", name: "Thorium", number: 90, description: "Used in nuclear reactors.", category: "actinide", column: 4, row: 10 },
    { symbol: "Pa", name: "Protactinium", number: 91, description: "Radioactive actinide.", category: "actinide", column: 5, row: 10 },
    { symbol: "U", name: "Uranium", number: 92, description: "Used in nuclear energy.", category: "actinide", column: 6, row: 10 },
    { symbol: "Np", name: "Neptunium", number: 93, description: "Radioactive actinide.", category: "actinide", column: 7, row: 10 },
    { symbol: "Pu", name: "Plutonium", number: 94, description: "Used in nuclear weapons.", category: "actinide", column: 8, row: 10 },
    { symbol: "Am", name: "Americium", number: 95, description: "Used in smoke detectors.", category: "actinide", column: 9, row: 10 },
    { symbol: "Cm", name: "Curium", number: 96, description: "Radioactive actinide.", category: "actinide", column: 10, row: 10 },
    { symbol: "Bk", name: "Berkelium", number: 97, description: "Synthetic actinide.", category: "actinide", column: 11, row: 10 },
    { symbol: "Cf", name: "Californium", number: 98, description: "Used in neutron sources.", category: "actinide", column: 12, row: 10 },
    { symbol: "Es", name: "Einsteinium", number: 99, description: "Synthetic element named after Einstein.", category: "actinide", column: 13, row: 10 },
    { symbol: "Fm", name: "Fermium", number: 100, description: "Synthetic element.", category: "actinide", column: 14, row: 10 },
    { symbol: "Md", name: "Mendelevium", number: 101, description: "Synthetic actinide.", category: "actinide", column: 15, row: 10 },
    { symbol: "No", name: "Nobelium", number: 102, description: "Synthetic element.", category: "actinide", column: 16, row: 10 },
    { symbol: "Lr", name: "Lawrencium", number: 103, description: "Last of the actinides.", category: "actinide", column: 17, row: 10 },
    { symbol: "Rf", name: "Rutherfordium", number: 104, description: "Synthetic transition metal.", category: "transition metal", column: 4, row: 7 },
    { symbol: "Db", name: "Dubnium", number: 105, description: "Synthetic transition metal.", category: "transition metal", column: 5, row: 7 },
    { symbol: "Sg", name: "Seaborgium", number: 106, description: "Synthetic element.", category: "transition metal", column: 6, row: 7 },
    { symbol: "Bh", name: "Bohrium", number: 107, description: "Synthetic element.", category: "transition metal", column: 7, row: 7 },
    { symbol: "Hs", name: "Hassium", number: 108, description: "Synthetic element.", category: "transition metal", column: 8, row: 7 },
    { symbol: "Mt", name: "Meitnerium", number: 109, description: "Synthetic element.", category: "unknown", column: 9, row: 7 },
    { symbol: "Ds", name: "Darmstadtium", number: 110, description: "Synthetic element.", category: "unknown", column: 10, row: 7 },
    { symbol: "Rg", name: "Roentgenium", number: 111, description: "Synthetic element.", category: "unknown", column: 11, row: 7 },
    { symbol: "Cn", name: "Copernicium", number: 112, description: "Synthetic element.", category: "transition metal", column: 12, row: 7 },
    { symbol: "Nh", name: "Nihonium", number: 113, description: "Synthetic element.", category: "post-transition metal", column: 13, row: 7 },
    { symbol: "Fl", name: "Flerovium", number: 114, description: "Synthetic element.", category: "post-transition metal", column: 14, row: 7 },
    { symbol: "Mc", name: "Moscovium", number: 115, description: "Synthetic element.", category: "post-transition metal", column: 15, row: 7 },
    { symbol: "Lv", name: "Livermorium", number: 116, description: "Synthetic element.", category: "post-transition metal", column: 16, row: 7 },
    { symbol: "Ts", name: "Tennessine", number: 117, description: "Synthetic element.", category: "halogen", column: 17, row: 7 },
    { symbol: "Uuo", name: "Oganesson", number: 118, description: "Superheavy element.", category: "noble gas", column: 18, row: 7 }
  ];
  
  const table = document.getElementById("periodic-table");
  
  elements.forEach((element) => {
    const div = document.createElement("div");
    div.className = `element ${element.category.replace(" ", "-")}`; // Add category-based class
    div.style.gridColumn = element.column;
    div.style.gridRow = element.row;
    div.innerHTML = `
      <strong>${element.symbol}</strong>
      <span>${element.number}</span>
      <div class="tooltip">
        <strong>${element.name}</strong><br>
        ${element.description}
      </div>
    `;
    table.appendChild(div);
  });
  